### ISSUE TITLE
Error with command `swig` during `sudo pip install python-u2flib-server`

### ISSUE THREAD

**Issue by ChickenNuggers** [Yubico/python-u2flib-server#16]
```
------------------------------------------------------------
/usr/bin/pip run on Wed Oct 21 22:02:07 2015
Requirement already satisfied (use --upgrade to upgrade): python-u2flib-server in /usr/local/lib/python2.7/dist-packages
Downloading/unpacking M2Crypto (from python-u2flib-server)
  Getting page https://pypi.python.org/simple/M2Crypto/
  URLs to search for versions for M2Crypto (from python-u2flib-server):
  * https://pypi.python.org/simple/M2Crypto/
  Analyzing links from page https://pypi.python.org/simple/m2crypto/
    Found link https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-0.17.tar.gz#md5=27272497ce13a3e78af028f7d0fd2d6f (from https://pypi.python.org/simple/m2crypto/), version: 0.17
    Found link https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-0.19.1.tar.gz#md5=c92286fdf0a75f017e72122c2832d5ff (from https://pypi.python.org/simple/m2crypto/), version: 0.19.1
    Found link https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-0.19.tar.gz#md5=f9fa8f38121be614d4d70e1884fcf260 (from https://pypi.python.org/simple/m2crypto/), version: 0.19
    Found link https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-0.20.1.tar.gz#md5=6a7420664310f424be4e63dfbe7e6e5f (from https://pypi.python.org/simple/m2crypto/), version: 0.20.1
    Found link https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-0.20.2.tar.gz#md5=6c24410410d6eb1920ea43f77a93613a (from https://pypi.python.org/simple/m2crypto/), version: 0.20.2
    Found link https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-0.20.tar.gz#md5=43a4d958a6c892a37ca02ffcc650b66b (from https://pypi.python.org/simple/m2crypto/), version: 0.20
    Found link https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-0.20beta1.tar.gz#md5=e1551fde39d75ebced9dd73b9a0ace50 (from https://pypi.python.org/simple/m2crypto/), version: 0.20beta1
    Found link https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-0.21.1.tar.gz#md5=f93d8462ff7646397a9f77a2fe602d17 (from https://pypi.python.org/simple/m2crypto/), version: 0.21.1
    Found link https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-0.21.tar.gz#md5=0057b9d04c821ebf3fdbadeb5a3acb36 (from https://pypi.python.org/simple/m2crypto/), version: 0.21
    Found link https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-0.22.3.tar.gz#md5=573f21aaac7d5c9549798e72ffcefedd (from https://pypi.python.org/simple/m2crypto/), version: 0.22.3
    Found link https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-0.22.4.tar.gz#md5=4998e9a27f90ad5ab98b77000f1c5f69 (from https://pypi.python.org/simple/m2crypto/), version: 0.22.4
    Found link https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-0.22.5.tar.gz#md5=f84eb07aa1687f39bc26ee7b1ba5a105 (from https://pypi.python.org/simple/m2crypto/), version: 0.22.5
    Found link https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-0.22.6rc1.tar.gz#md5=3c689818e435789da406eb59bed8f2fb (from https://pypi.python.org/simple/m2crypto/), version: 0.22.6rc1
    Found link https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-0.22.6rc2.tar.gz#md5=019802df9507447c580ac2e015ea53d5 (from https://pypi.python.org/simple/m2crypto/), version: 0.22.6rc2
    Found link https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-0.22.6rc3.tar.gz#md5=c650e0f6958d9e1ccb73a0369fbf23c8 (from https://pypi.python.org/simple/m2crypto/), version: 0.22.6rc3
    Found link https://pypi.python.org/packages/source/M/M2Crypto/m2crypto-0.15.tar.gz#md5=6a31501dc11cdfd9380ec4a18d461fd9 (from https://pypi.python.org/simple/m2crypto/), version: 0.15
    Found link https://pypi.python.org/packages/source/M/M2Crypto/m2crypto-0.16.tar.gz#md5=6fc06583a2be56fc2a46872a0540d78e (from https://pypi.python.org/simple/m2crypto/), version: 0.16
    Found link https://pypi.python.org/packages/source/M/M2Crypto/m2crypto-0.18.1.tar.gz#md5=c6e8fa402d920da08b0459dd5755a386 (from https://pypi.python.org/simple/m2crypto/), version: 0.18.1
    Found link https://pypi.python.org/packages/source/M/M2Crypto/m2crypto-0.18.2.tar.gz#md5=445dce53fcfc7ec8f6fd31f54da8a067 (from https://pypi.python.org/simple/m2crypto/), version: 0.18.2
    Found link https://pypi.python.org/packages/source/M/M2Crypto/m2crypto-0.18.tar.gz#md5=4e5432d08fd50287b80ac2237f01bda3 (from https://pypi.python.org/simple/m2crypto/), version: 0.18
  Ignoring link https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-0.20beta1.tar.gz#md5=e1551fde39d75ebced9dd73b9a0ace50 (from https://pypi.python.org/simple/m2crypto/), version 0.20beta1 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-0.22.6rc1.tar.gz#md5=3c689818e435789da406eb59bed8f2fb (from https://pypi.python.org/simple/m2crypto/), version 0.22.6rc1 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-0.22.6rc2.tar.gz#md5=019802df9507447c580ac2e015ea53d5 (from https://pypi.python.org/simple/m2crypto/), version 0.22.6rc2 is a pre-release (use --pre to allow).
  Ignoring link https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-0.22.6rc3.tar.gz#md5=c650e0f6958d9e1ccb73a0369fbf23c8 (from https://pypi.python.org/simple/m2crypto/), version 0.22.6rc3 is a pre-release (use --pre to allow).
  Using version 0.22.5 (newest of versions: 0.22.5, 0.22.4, 0.22.3, 0.21.1, 0.21, 0.20.2, 0.20.1, 0.20, 0.19.1, 0.19, 0.18.2, 0.18.1, 0.18, 0.17, 0.16, 0.15)
  Downloading from URL https://pypi.python.org/packages/source/M/M2Crypto/M2Crypto-0.22.5.tar.gz#md5=f84eb07aa1687f39bc26ee7b1ba5a105 (from https://pypi.python.org/simple/m2crypto/)
  Running setup.py (path:/tmp/pip-build-_oTf56/M2Crypto/setup.py) egg_info for package M2Crypto
    running egg_info
    creating pip-egg-info/M2Crypto.egg-info
    writing pip-egg-info/M2Crypto.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/M2Crypto.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/M2Crypto.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/M2Crypto.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pip-egg-info/M2Crypto.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files found matching 'M2Crypto/_m2crypto.py'
    writing manifest file 'pip-egg-info/M2Crypto.egg-info/SOURCES.txt'
  Source in /tmp/pip-build-_oTf56/M2Crypto has version 0.22.5, which satisfies requirement M2Crypto (from python-u2flib-server)
Requirement already satisfied (use --upgrade to upgrade): pyasn1>=0.1.7 in /usr/lib/python2.7/dist-packages (from python-u2flib-server)
Requirement already satisfied (use --upgrade to upgrade): pyasn1-modules in /usr/lib/python2.7/dist-packages (from python-u2flib-server)
Installing collected packages: M2Crypto
  Running setup.py install for M2Crypto
    Running command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-_oTf56/M2Crypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-W6QvT3-record/install-record.txt --single-version-externally-managed --compile
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/util.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/threading.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/EVP.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/ftpslib.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/DSA.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/m2xmlrpclib.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/m2.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/callback.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/BN.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/SMIME.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/Rand.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/AuthCookie.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/RC4.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/ASN1.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/Err.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/BIO.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/m2urllib2.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/EC.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/RSA.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/m2urllib.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/X509.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/Engine.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/__init__.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/httpslib.py -> build/lib.linux-x86_64-2.7/M2Crypto
    copying M2Crypto/DH.py -> build/lib.linux-x86_64-2.7/M2Crypto
    creating build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/cb.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/Session.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/SSLServer.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/Cipher.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/Connection.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/Checker.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/Context.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/TwistedProtocolWrapper.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/__init__.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/ssl_dispatcher.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    copying M2Crypto/SSL/timeout.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL
    creating build/lib.linux-x86_64-2.7/M2Crypto/PGP
    copying M2Crypto/PGP/constants.py -> build/lib.linux-x86_64-2.7/M2Crypto/PGP
    copying M2Crypto/PGP/PublicKeyRing.py -> build/lib.linux-x86_64-2.7/M2Crypto/PGP
    copying M2Crypto/PGP/PublicKey.py -> build/lib.linux-x86_64-2.7/M2Crypto/PGP
    copying M2Crypto/PGP/packet.py -> build/lib.linux-x86_64-2.7/M2Crypto/PGP
    copying M2Crypto/PGP/RSA.py -> build/lib.linux-x86_64-2.7/M2Crypto/PGP
    copying M2Crypto/PGP/__init__.py -> build/lib.linux-x86_64-2.7/M2Crypto/PGP
    running build_ext
    building 'M2Crypto.__m2crypto' extension
    swigging SWIG/_m2crypto.i to SWIG/_m2crypto_wrap.c
    swig -python -I/usr/include/python2.7 -I/usr/include -includeall -modern -builtin -outdir build/lib.linux-x86_64-2.7/M2Crypto -o SWIG/_m2crypto_wrap.c SWIG/_m2crypto.i
    SWIG/_evp.i:12: Error: Unable to find 'openssl/opensslconf.h'
    SWIG/_ec.i:7: Error: Unable to find 'openssl/opensslconf.h'
    error: command 'swig' failed with exit status 1
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-_oTf56/M2Crypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-W6QvT3-record/install-record.txt --single-version-externally-managed --compile:
    running install

running build

running build_py

creating build

creating build/lib.linux-x86_64-2.7

creating build/lib.linux-x86_64-2.7/M2Crypto

copying M2Crypto/util.py -> build/lib.linux-x86_64-2.7/M2Crypto

copying M2Crypto/threading.py -> build/lib.linux-x86_64-2.7/M2Crypto

copying M2Crypto/EVP.py -> build/lib.linux-x86_64-2.7/M2Crypto

copying M2Crypto/ftpslib.py -> build/lib.linux-x86_64-2.7/M2Crypto

copying M2Crypto/DSA.py -> build/lib.linux-x86_64-2.7/M2Crypto

copying M2Crypto/m2xmlrpclib.py -> build/lib.linux-x86_64-2.7/M2Crypto

copying M2Crypto/m2.py -> build/lib.linux-x86_64-2.7/M2Crypto

copying M2Crypto/callback.py -> build/lib.linux-x86_64-2.7/M2Crypto

copying M2Crypto/BN.py -> build/lib.linux-x86_64-2.7/M2Crypto

copying M2Crypto/SMIME.py -> build/lib.linux-x86_64-2.7/M2Crypto

copying M2Crypto/Rand.py -> build/lib.linux-x86_64-2.7/M2Crypto

copying M2Crypto/AuthCookie.py -> build/lib.linux-x86_64-2.7/M2Crypto

copying M2Crypto/RC4.py -> build/lib.linux-x86_64-2.7/M2Crypto

copying M2Crypto/ASN1.py -> build/lib.linux-x86_64-2.7/M2Crypto

copying M2Crypto/Err.py -> build/lib.linux-x86_64-2.7/M2Crypto

copying M2Crypto/BIO.py -> build/lib.linux-x86_64-2.7/M2Crypto

copying M2Crypto/m2urllib2.py -> build/lib.linux-x86_64-2.7/M2Crypto

copying M2Crypto/EC.py -> build/lib.linux-x86_64-2.7/M2Crypto

copying M2Crypto/RSA.py -> build/lib.linux-x86_64-2.7/M2Crypto

copying M2Crypto/m2urllib.py -> build/lib.linux-x86_64-2.7/M2Crypto

copying M2Crypto/X509.py -> build/lib.linux-x86_64-2.7/M2Crypto

copying M2Crypto/Engine.py -> build/lib.linux-x86_64-2.7/M2Crypto

copying M2Crypto/__init__.py -> build/lib.linux-x86_64-2.7/M2Crypto

copying M2Crypto/httpslib.py -> build/lib.linux-x86_64-2.7/M2Crypto

copying M2Crypto/DH.py -> build/lib.linux-x86_64-2.7/M2Crypto

creating build/lib.linux-x86_64-2.7/M2Crypto/SSL

copying M2Crypto/SSL/cb.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL

copying M2Crypto/SSL/Session.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL

copying M2Crypto/SSL/SSLServer.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL

copying M2Crypto/SSL/Cipher.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL

copying M2Crypto/SSL/Connection.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL

copying M2Crypto/SSL/Checker.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL

copying M2Crypto/SSL/Context.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL

copying M2Crypto/SSL/TwistedProtocolWrapper.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL

copying M2Crypto/SSL/__init__.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL

copying M2Crypto/SSL/ssl_dispatcher.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL

copying M2Crypto/SSL/timeout.py -> build/lib.linux-x86_64-2.7/M2Crypto/SSL

creating build/lib.linux-x86_64-2.7/M2Crypto/PGP

copying M2Crypto/PGP/constants.py -> build/lib.linux-x86_64-2.7/M2Crypto/PGP

copying M2Crypto/PGP/PublicKeyRing.py -> build/lib.linux-x86_64-2.7/M2Crypto/PGP

copying M2Crypto/PGP/PublicKey.py -> build/lib.linux-x86_64-2.7/M2Crypto/PGP

copying M2Crypto/PGP/packet.py -> build/lib.linux-x86_64-2.7/M2Crypto/PGP

copying M2Crypto/PGP/RSA.py -> build/lib.linux-x86_64-2.7/M2Crypto/PGP

copying M2Crypto/PGP/__init__.py -> build/lib.linux-x86_64-2.7/M2Crypto/PGP

running build_ext

building 'M2Crypto.__m2crypto' extension

swigging SWIG/_m2crypto.i to SWIG/_m2crypto_wrap.c

swig -python -I/usr/include/python2.7 -I/usr/include -includeall -modern -builtin -outdir build/lib.linux-x86_64-2.7/M2Crypto -o SWIG/_m2crypto_wrap.c SWIG/_m2crypto.i

SWIG/_evp.i:12: Error: Unable to find 'openssl/opensslconf.h'

SWIG/_ec.i:7: Error: Unable to find 'openssl/opensslconf.h'

error: command 'swig' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-_oTf56/M2Crypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-W6QvT3-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-_oTf56/M2Crypto
Exception information:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 295, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 707, in install
    cwd=self.source_dir, filter_stdout=self._filter_install, show_stdout=False)
  File "/usr/lib/python2.7/dist-packages/pip/util.py", line 716, in call_subprocess
    % (command_desc, proc.returncode, cwd))
InstallationError: Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-_oTf56/M2Crypto/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-W6QvT3-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-_oTf56/M2Crypto
```

I've gotten this error with SWIG 2.0 and 3.0.
The SWIG 2.0 was on my Debian server, Python 2.7 default, with libssl-dev installed.
The SWIG 3.0 was on my Arch home laptop, Python 3.5 default, with openssl installed.

**Comment by ChickenNuggers** [comment]
`/usr/include/x86_64-linux-gnu/openssl/opensslconf.h` - Debian `opensslconf.h`
`/usr/include/openssl/opensslconf.h` - Arch `opensslconf.h`

Trying it now, it seems to install correctly on Arch, but I get: `ImportError: No module named M2Crypto`
I'm guessing this is an error with Arch automatically assuming Python3 instead of Python2, but when trying Python3 instead, I get: `ImportError: No module named '_m2crypto'`
I get the same thing in Python2 if I try `import _m2crypto`

**Comment by ChickenNuggers** [comment]
```
  Running setup.py (path:/tmp/pip-build-_oTf56/M2Crypto/setup.py) egg_info for package M2Crypto
    running egg_info
    creating pip-egg-info/M2Crypto.egg-info
    writing pip-egg-info/M2Crypto.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/M2Crypto.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/M2Crypto.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/M2Crypto.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info/M2Crypto.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files found matching 'M2Crypto/_m2crypto.py'
    writing manifest file 'pip-egg-info/M2Crypto.egg-info/SOURCES.txt'
```
I'm looking at: `warning: manifest_maker: standard file '-c' not found` - I think this is an issue?

**Comment by ChickenNuggers** [comment]
https://github.com/letsencrypt/letsencrypt/issues/37 says something about including from `/usr/include/x86_64-linux-gnu`

**Comment by gavinwahl** [comment]
This is fixed, python-u2flib-server no longer depends on m2crypto.

**Comment by ChickenNuggers** [comment]
Cool.
