### ISSUE TITLE
Can't install from source 

### ISSUE THREAD

**Issue by gavinwahl** [Yubico/python-u2flib-server#26]
pip install -e ~/python-u2flib-server

~~~
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "python-u2flib-server/setup.py", line 28, in <module>
        from u2flib_server.yubicommon.setup import setup
    ImportError: No module named yubicommon.setup
    
    ----------------------------------------
~~~~

**Comment by gavinwahl** [comment]
Sorry, nevermind, I missed the mention of the submodule in the readme.
