### ISSUE TITLE
TypeError: initializer for ctype 'char' must be a bytes of length 1, not int

### ISSUE THREAD

**Issue by gavinwahl** [Yubico/python-u2flib-server#29]
I'm getting an error when calling complete_register:

```pytb
Traceback (most recent call last):
  ...
  File "django-u2f/django_u2f/views.py", line 127, in form_valid
    device, attestation_cert = u2f.complete_register(challenge, response)
  File "u2flib_server/u2f_v2.py", line 208, in complete_register
    response.registrationData
  File "/home/gavin/.virtualenvs/lottery/lib/python3.5/site-packages/u2flib_server/u2f_v2.py", line 89, in __init__
    self.certificate = self._fixsig(certificate_from_der(data))
  File "u2flib_server/u2f_v2.py", line 111, in _fixsig
    cert = certificate_from_der(der)
  File "u2flib_server/utils.py", line 47, in certificate_from_der
    return x509.load_der_x509_certificate(der, default_backend())
  File "cryptography/x509/base.py", line 32, in load_der_x509_certificate
    return backend.load_der_x509_certificate(data)
  File "cryptography/hazmat/backends/multibackend.py", line 334, in load_der_x509_certificate
    return b.load_der_x509_certificate(data)
  File "cryptography/hazmat/backends/openssl/backend.py", line 1193, in load_der_x509_certificate
    mem_bio = self._bytes_to_bio(data)
  File "cryptography/hazmat/backends/openssl/backend.py", line 477, in _bytes_to_bio
    data_char_p = self._ffi.new("char[]", data)
TypeError: initializer for ctype 'char' must be a bytes of length 1, not int
```

This is on python 3.5. I'm not sure whether this should be reported here or in cryptography.

Looks like the problem might be in RawRegistrationResponse._fixsig. It calls list() on a bytestring to convert it to a list of integers, but never converts the list back to a bytestring. This patch does "fix" the issue, but I don't know if it's the correct solution and probably doesn't work on python 2:

```patch
diff --git a/u2flib_server/u2f_v2.py b/u2flib_server/u2f_v2.py
index 52793bf..3851871 100644
--- a/u2flib_server/u2f_v2.py
+++ b/u2flib_server/u2f_v2.py
@@ -107,8 +107,8 @@ class RawRegistrationResponse(object):
 
         if subject in FIXSIG:  # Set unused bits in signature to 0
             der = list(cert.public_bytes(Encoding.DER))
-            der[-257] = b'\x00'
-            cert = certificate_from_der(der)
+            der[-257] = 0
+            cert = certificate_from_der(bytes(der))
         return cert
 
     def serialize(self):
```

**Comment by dainnilsson** [comment]
Thanks, this should be fixed by 0ebf97a!

**Comment by gavinwahl** [comment]
This fixed it, thanks!

**Comment by gavinwahl** [comment]
Is there a release planned soon?

**Comment by dainnilsson** [comment]
Done: https://pypi.python.org/pypi/python-u2flib-server/4.0.1

**Comment by gavinwahl** [comment]
Thanks!
